Fix cb?.() syntax
pinojs/sonic-boom pull request #198
Opened 2024-06-03 19:43 UTC by tedyu

This PR tries to fix the following compilation error:

/opt/app/node_modules/sonic-boom/index.js:393
    cb?.()
       ^

SyntaxError: Invalid or unexpected token
    at Object.replacementCompile (/opt/app/node_modules/append-transform/index.js:60:13)

2024-06-04 07:35 UTC, mcollina requested changes
Could you add a test for this? I have not understood why this happens to begin with. All our tests pass.

2024-06-07 00:00 UTC, tedyu commented
@mcollina 
This change is semantically equivalent.
It will allow downstream projects to avoid `Invalid or unexpected token` error.

2024-06-07 10:18 UTC, tedyu commented
Our services depend on `sonic-boom` via `pino`.
Recently I downgraded `pino` release in our service due to the `Invalid or unexpected token` error mentioned in the description.

2024-06-07 11:13 UTC, jsumners commented
How can the error be reproduced? We need that reproduction in our test suite. Otherwise, this is supported syntax on all of the Node.js versions we target.

2024-07-02 18:43 UTC, tedyu commented
Looking at the build error:
```
/opt/app/node_modules/sonic-boom/index.js:393
    cb?.()
       ^

SyntaxError: Invalid or unexpected token
    at Object.replacementCompile (/opt/app/node_modules/append-transform/index.js:60:13)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at /opt/app/node_modules/append-transform/index.js:64:4
```
It seems `append-transform` doesn't accept optional chaining.

@jsumners @mcollina Have you seen any user reporting similar issue ?

Thanks

2024-07-02 18:47 UTC, jsumners commented
What is `append-transform`?

2024-07-02 18:51 UTC, tedyu commented
According to https://www.npmjs.com/package/append-transform 

Install a transform to require.extensions that always runs last, even if additional extensions are added later

2024-07-02 19:00 UTC, tedyu commented
@jsumners 
With the proposed change, users of `sonic-boom` (along with `append-transform`) wouldn't need to worry about configuration.

2024-07-03 10:26 UTC, jsumners commented
I'll let @mcollina have the final word. In my view, the reason a reproduction cannot be added to the tests is because there is not a bug here. The newly provided information clearly indicates there is a bug in some other package.

2024-07-03 14:11 UTC, tedyu commented
My coworker has agreed for us to downgrade `pino` release so that we don't have to spend time on tuning `append-transform`.
My PR would allow us (and other users who meet similar error) to upgrade to newer `pino` release.
Note: our node version is 18.

2024-07-03 14:37 UTC, mcollina commented
Unless a test is added, it's _very likely_ we will regress. Closing for now. Feel free to reopen if you can provide a test.

2024-07-03 14:37 UTC, closed without merging